#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
set timeout=1
set default=1
menuentry "Linux" {
    set root=(hd0,1)
    linux /vmlinuz label=boot root=__ROOTFS__ rw __VIDEO_MODE__ __VGA_MODE__ quiet
    initrd /initrd
}
